"""
    Yourkeys Public API

    This API exposes endpoints that can be used to interact with the Yourkeys system  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: support@yourkeys.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import yk_client
from yk_client.model.valuation_instruction import ValuationInstruction
globals()['ValuationInstruction'] = ValuationInstruction
from yk_client.model.valuation_instruction_request import ValuationInstructionRequest


class TestValuationInstructionRequest(unittest.TestCase):
    """ValuationInstructionRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testValuationInstructionRequest(self):
        """Test ValuationInstructionRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ValuationInstructionRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
