"""
    Yourkeys Public API

    This API exposes endpoints that can be used to interact with the Yourkeys system  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: support@yourkeys.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.onfido_api import OnfidoApi  # noqa: E501


class TestOnfidoApi(unittest.TestCase):
    """OnfidoApi unit test stubs"""

    def setUp(self):
        self.api = OnfidoApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_onfido_webhook_post(self):
        """Test case for api_onfido_webhook_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
