"""
    Yourkeys Public API

    This API exposes endpoints that can be used to interact with the Yourkeys system  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: support@yourkeys.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.seller_api import SellerApi  # noqa: E501


class TestSellerApi(unittest.TestCase):
    """SellerApi unit test stubs"""

    def setUp(self):
        self.api = SellerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_seller_reference_number_developments_development_id_plots_get(self):
        """Test case for api_seller_reference_number_developments_development_id_plots_get

        Returns all plots with an AVABL status for a the supplied development that the supplied seller has access to.  # noqa: E501
        """
        pass

    def test_api_seller_reference_number_developments_get(self):
        """Test case for api_seller_reference_number_developments_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
