"""
    Yourkeys Public API

    This API exposes endpoints that can be used to interact with the Yourkeys system  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: support@yourkeys.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.logo_api import LogoApi  # noqa: E501


class TestLogoApi(unittest.TestCase):
    """LogoApi unit test stubs"""

    def setUp(self):
        self.api = LogoApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_logo_development_main_account_development_id_get(self):
        """Test case for logo_development_main_account_development_id_get

        """
        pass

    def test_logo_seller_developer_id_get(self):
        """Test case for logo_seller_developer_id_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
