"""
    Yourkeys Public API

    This API exposes endpoints that can be used to interact with the Yourkeys system  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: support@yourkeys.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.create_block_response import CreateBlockResponse
globals()['CreateBlockResponse'] = CreateBlockResponse
from openapi_client.model.create_blocks_response import CreateBlocksResponse


class TestCreateBlocksResponse(unittest.TestCase):
    """CreateBlocksResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateBlocksResponse(self):
        """Test CreateBlocksResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CreateBlocksResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
