"""
    Yourkeys Public API

    This API exposes endpoints that can be used to interact with the Yourkeys system  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: support@yourkeys.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.create_plot_request import CreatePlotRequest
globals()['CreatePlotRequest'] = CreatePlotRequest
from openapi_client.model.create_plots_request import CreatePlotsRequest


class TestCreatePlotsRequest(unittest.TestCase):
    """CreatePlotsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreatePlotsRequest(self):
        """Test CreatePlotsRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CreatePlotsRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
