"""
    Yourkeys Public API

    This API exposes endpoints that can be used to interact with the Yourkeys system  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: support@yourkeys.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.create_development_request import CreateDevelopmentRequest
globals()['CreateDevelopmentRequest'] = CreateDevelopmentRequest
from openapi_client.model.create_developments_request import CreateDevelopmentsRequest


class TestCreateDevelopmentsRequest(unittest.TestCase):
    """CreateDevelopmentsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateDevelopmentsRequest(self):
        """Test CreateDevelopmentsRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CreateDevelopmentsRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
