"""
    Yourkeys Public API

    This API exposes endpoints that can be used to interact with the Yourkeys system  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: support@yourkeys.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.documents_api import DocumentsApi  # noqa: E501


class TestDocumentsApi(unittest.TestCase):
    """DocumentsApi unit test stubs"""

    def setUp(self):
        self.api = DocumentsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_reservation_referencenumber_documents_instructionpack_fileid_get(self):
        """Test case for api_reservation_referencenumber_documents_instructionpack_fileid_get

        """
        pass

    def test_api_reservation_referencenumber_documents_instructionpack_get(self):
        """Test case for api_reservation_referencenumber_documents_instructionpack_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
