"""
    Yourkeys Public API

    This API exposes endpoints that can be used to interact with the Yourkeys system  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: support@yourkeys.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import yk_client
from yk_client.model.valuation_received import ValuationReceived
globals()['ValuationReceived'] = ValuationReceived
from yk_client.model.valuation_received_request import ValuationReceivedRequest


class TestValuationReceivedRequest(unittest.TestCase):
    """ValuationReceivedRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testValuationReceivedRequest(self):
        """Test ValuationReceivedRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ValuationReceivedRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
