"""
    Yourkeys Public API

    This API exposes endpoints that can be used to interact with the Yourkeys system  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: support@yourkeys.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.client import Client
from openapi_client.model.purchase_path import PurchasePath
globals()['Client'] = Client
globals()['PurchasePath'] = PurchasePath
from openapi_client.model.create_reservation_request import CreateReservationRequest


class TestCreateReservationRequest(unittest.TestCase):
    """CreateReservationRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateReservationRequest(self):
        """Test CreateReservationRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CreateReservationRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
