"""
    Yourkeys Public API

    This API exposes endpoints that can be used to interact with the Yourkeys system  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: support@yourkeys.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.cml_construction_request import CmlConstructionRequest
from openapi_client.model.cml_freeholder_request import CmlFreeholderRequest
from openapi_client.model.cml_seller_details_request import CmlSellerDetailsRequest
from openapi_client.model.cml_separate_lease_ground_rent_details_request import CmlSeparateLeaseGroundRentDetailsRequest
from openapi_client.model.cml_tenure_request import CmlTenureRequest
from openapi_client.model.cml_warranty_professional_consultant_accreditation_request import CmlWarrantyProfessionalConsultantAccreditationRequest
globals()['CmlConstructionRequest'] = CmlConstructionRequest
globals()['CmlFreeholderRequest'] = CmlFreeholderRequest
globals()['CmlSellerDetailsRequest'] = CmlSellerDetailsRequest
globals()['CmlSeparateLeaseGroundRentDetailsRequest'] = CmlSeparateLeaseGroundRentDetailsRequest
globals()['CmlTenureRequest'] = CmlTenureRequest
globals()['CmlWarrantyProfessionalConsultantAccreditationRequest'] = CmlWarrantyProfessionalConsultantAccreditationRequest
from openapi_client.model.create_cml_request import CreateCmlRequest


class TestCreateCmlRequest(unittest.TestCase):
    """CreateCmlRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateCmlRequest(self):
        """Test CreateCmlRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CreateCmlRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
