"""
    Yourkeys Public API

    This API exposes endpoints that can be used to interact with the Yourkeys system  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: support@yourkeys.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.update_development_response import UpdateDevelopmentResponse
globals()['UpdateDevelopmentResponse'] = UpdateDevelopmentResponse
from openapi_client.model.update_developments_response import UpdateDevelopmentsResponse


class TestUpdateDevelopmentsResponse(unittest.TestCase):
    """UpdateDevelopmentsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUpdateDevelopmentsResponse(self):
        """Test UpdateDevelopmentsResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UpdateDevelopmentsResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
