"""
    Yourkeys Public API

    This API exposes endpoints that can be used to interact with the Yourkeys system  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: support@yourkeys.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.event_api import EventApi  # noqa: E501


class TestEventApi(unittest.TestCase):
    """EventApi unit test stubs"""

    def setUp(self):
        self.api = EventApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_progression_purchase_referencenumber_event_eventcode_put(self):
        """Test case for api_progression_purchase_referencenumber_event_eventcode_put

        """
        pass


if __name__ == '__main__':
    unittest.main()
