"""
    Yourkeys Public API

    This API exposes endpoints that can be used to interact with the Yourkeys system  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: support@yourkeys.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.set_development_live_flag_request import SetDevelopmentLiveFlagRequest


class TestSetDevelopmentLiveFlagRequest(unittest.TestCase):
    """SetDevelopmentLiveFlagRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSetDevelopmentLiveFlagRequest(self):
        """Test SetDevelopmentLiveFlagRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SetDevelopmentLiveFlagRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
