"""
    Yourkeys Public API

    This API exposes endpoints that can be used to interact with the Yourkeys system  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: support@yourkeys.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import yk_client
from yk_client.model.mortgage_offer_issued import MortgageOfferIssued


class TestMortgageOfferIssued(unittest.TestCase):
    """MortgageOfferIssued unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMortgageOfferIssued(self):
        """Test MortgageOfferIssued"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MortgageOfferIssued()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
