"""
    Yourkeys Public API

    This API exposes endpoints that can be used to interact with the Yourkeys system  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: support@yourkeys.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.update_block_response import UpdateBlockResponse
globals()['UpdateBlockResponse'] = UpdateBlockResponse
from openapi_client.model.update_blocks_response import UpdateBlocksResponse


class TestUpdateBlocksResponse(unittest.TestCase):
    """UpdateBlocksResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUpdateBlocksResponse(self):
        """Test UpdateBlocksResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UpdateBlocksResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
