"""
    Yourkeys Public API

    This API exposes endpoints that can be used to interact with the Yourkeys system  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: support@yourkeys.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.inventory_api import InventoryApi  # noqa: E501


class TestInventoryApi(unittest.TestCase):
    """InventoryApi unit test stubs"""

    def setUp(self):
        self.api = InventoryApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_inventory_blocks_delete(self):
        """Test case for api_inventory_blocks_delete

        """
        pass

    def test_api_inventory_blocks_post(self):
        """Test case for api_inventory_blocks_post

        """
        pass

    def test_api_inventory_blocks_put(self):
        """Test case for api_inventory_blocks_put

        """
        pass

    def test_api_inventory_development_livestatusupdate_put(self):
        """Test case for api_inventory_development_livestatusupdate_put

        """
        pass

    def test_api_inventory_developments_post(self):
        """Test case for api_inventory_developments_post

        """
        pass

    def test_api_inventory_developments_put(self):
        """Test case for api_inventory_developments_put

        """
        pass

    def test_api_inventory_housebuilder_seller_reference_development_development_id_block_block_id_plots_get(self):
        """Test case for api_inventory_housebuilder_seller_reference_development_development_id_block_block_id_plots_get

        """
        pass

    def test_api_inventory_housebuilder_seller_reference_development_development_id_blocks_get(self):
        """Test case for api_inventory_housebuilder_seller_reference_development_development_id_blocks_get

        """
        pass

    def test_api_inventory_housebuilder_seller_reference_developments_get(self):
        """Test case for api_inventory_housebuilder_seller_reference_developments_get

        """
        pass

    def test_api_inventory_plots_delete(self):
        """Test case for api_inventory_plots_delete

        """
        pass

    def test_api_inventory_plots_post(self):
        """Test case for api_inventory_plots_post

        """
        pass

    def test_api_inventory_plots_put(self):
        """Test case for api_inventory_plots_put

        """
        pass


if __name__ == '__main__':
    unittest.main()
