"""
    Yourkeys Public API

    This API exposes endpoints that can be used to interact with the Yourkeys system  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: support@yourkeys.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.passthrough_api import PassthroughApi  # noqa: E501


class TestPassthroughApi(unittest.TestCase):
    """PassthroughApi unit test stubs"""

    def setUp(self):
        self.api = PassthroughApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_passthrough_generate_passthrough_url_post(self):
        """Test case for api_passthrough_generate_passthrough_url_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
