"""
    Yourkeys Public API

    This API exposes endpoints that can be used to interact with the Yourkeys system  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: support@yourkeys.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.regression_api import RegressionApi  # noqa: E501


class TestRegressionApi(unittest.TestCase):
    """RegressionApi unit test stubs"""

    def setUp(self):
        self.api = RegressionApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_regression_purchase_referencenumber_code_delete(self):
        """Test case for api_regression_purchase_referencenumber_code_delete

        """
        pass

    def test_api_regression_purchase_referencenumber_last_delete(self):
        """Test case for api_regression_purchase_referencenumber_last_delete

        """
        pass


if __name__ == '__main__':
    unittest.main()
