"""
    Yourkeys Public API

    This API exposes endpoints that can be used to interact with the Yourkeys system  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: support@yourkeys.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.update_block_request import UpdateBlockRequest
globals()['UpdateBlockRequest'] = UpdateBlockRequest
from openapi_client.model.update_blocks_request import UpdateBlocksRequest


class TestUpdateBlocksRequest(unittest.TestCase):
    """UpdateBlocksRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUpdateBlocksRequest(self):
        """Test UpdateBlocksRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UpdateBlocksRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
