"""
    Yourkeys Public API

    This API exposes endpoints that can be used to interact with the Yourkeys system  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: support@yourkeys.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.create_cml_request import CreateCmlRequest
globals()['CreateCmlRequest'] = CreateCmlRequest
from openapi_client.model.create_development_request import CreateDevelopmentRequest


class TestCreateDevelopmentRequest(unittest.TestCase):
    """CreateDevelopmentRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateDevelopmentRequest(self):
        """Test CreateDevelopmentRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CreateDevelopmentRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
