"""
    Yourkeys Public API

    This API exposes endpoints that can be used to interact with the Yourkeys system  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: support@yourkeys.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.sales_api import SalesApi  # noqa: E501


class TestSalesApi(unittest.TestCase):
    """SalesApi unit test stubs"""

    def setUp(self):
        self.api = SalesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_reservation_post(self):
        """Test case for api_reservation_post

        """
        pass

    def test_api_sales_reservation_post(self):
        """Test case for api_sales_reservation_post

        """
        pass

    def test_api_sales_reservation_upgrades_and_extras_post(self):
        """Test case for api_sales_reservation_upgrades_and_extras_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
