"""
    Yourkeys Public API

    This API exposes endpoints that can be used to interact with the Yourkeys system  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: support@yourkeys.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.progression_api import ProgressionApi  # noqa: E501


class TestProgressionApi(unittest.TestCase):
    """ProgressionApi unit test stubs"""

    def setUp(self):
        self.api = ProgressionApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_progression_purchase_referencenumber_code_put(self):
        """Test case for api_progression_purchase_referencenumber_code_put

        """
        pass


if __name__ == '__main__':
    unittest.main()
