"""
    Yourkeys Public API

    This API exposes endpoints that can be used to interact with the Yourkeys system  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: support@yourkeys.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.seller_development_response import SellerDevelopmentResponse
globals()['SellerDevelopmentResponse'] = SellerDevelopmentResponse
from openapi_client.model.seller_developments_response import SellerDevelopmentsResponse


class TestSellerDevelopmentsResponse(unittest.TestCase):
    """SellerDevelopmentsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSellerDevelopmentsResponse(self):
        """Test SellerDevelopmentsResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SellerDevelopmentsResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
