"""
    Yourkeys Public API

    This API exposes endpoints that can be used to interact with the Yourkeys system  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: support@yourkeys.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.get_plot_response import GetPlotResponse
globals()['GetPlotResponse'] = GetPlotResponse
from openapi_client.model.get_plots_response import GetPlotsResponse


class TestGetPlotsResponse(unittest.TestCase):
    """GetPlotsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetPlotsResponse(self):
        """Test GetPlotsResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetPlotsResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
