"""
    Yourkeys Public API

    This API exposes endpoints that can be used to interact with the Yourkeys system  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: support@yourkeys.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.create_plot_response import CreatePlotResponse
globals()['CreatePlotResponse'] = CreatePlotResponse
from openapi_client.model.create_plots_response import CreatePlotsResponse


class TestCreatePlotsResponse(unittest.TestCase):
    """CreatePlotsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreatePlotsResponse(self):
        """Test CreatePlotsResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CreatePlotsResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
